name: CI

on:
  push:
    branches: [ origin ]


jobs:
  integration_edex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman tests/integration_edex.json 